### ISSUE TITLE
How do I compile hdt-it?

### ISSUE THREAD

**Issue by noumlaut** [rdfhdt/hdt-cpp#60]
There doesn't seem to be any Makefile available.

**Comment by wouterbeek** [comment]
See `/hdt-lib`.

**Comment by webdata** [comment]
Hi, if you mean the hdt-it visualization tool, I included a new README with all the information: https://github.com/rdfhdt/hdt-cpp/tree/master/hdt-it

**Comment by noumlaut** [comment]
I can compile `libcds` and `hdt-lib` but not `hdt-it`. The error I get is this one:

```
g++ -c -pipe -O3 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../libcds-v1.0.12/includes -I../hdt-lib/include -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -Iunix -Iunix -I/usr/lib64/qt5/mkspecs/linux-g++ -o unix/main.o main.cpp
In file included from myapplication.hpp:5:0,
                 from main.cpp:5:
hdtit.hpp:18:1: error: expected class-name before ‘{’ token
 {
 ^
hdtit.hpp:26:5: error: ‘QTableView’ does not name a type
     QTableView *lastContextMenuTable;
     ^~~~~~~~~~
main.cpp: In function ‘int main(int, char**)’:
main.cpp:31:7: error: ‘class HDTit’ has no member named ‘show’
     w.show();
       ^~~~
Makefile.Release:972: recipe for target 'unix/main.o' failed
make[1]: *** [unix/main.o] Error 1
```

I'm using Fedora and Qt5.

**Comment by noumlaut** [comment]
If instead I use Qt4, I get this error when compiling HDT-it (after compiling the other two)

```
make[1]: *** No rule to make target '../libcds-v1.0.12/lib/libcds.a', needed by 'unix/HDT-it'.  Stop.
```

**Comment by MarioAriasGa** [comment]
Hi noumlaut, I just pushed some changes so it compiles with Qt5.8. I have tried under windows and mac but not under linux. Please let me know if you find any issue.

**Comment by noumlaut** [comment]
In which branch? I don't see any new commits in `master`.

**Comment by MarioAriasGa** [comment]
Sorry, in branch `develop`

**Comment by noumlaut** [comment]
OK, compiled. Can merge to `master` I guess :)

Cheers.
