### ISSUE TITLE
Error compiling test on Ubuntu 14.04 LTS 64 bit

### ISSUE THREAD

**Issue by CristianCantoro** [rdfhdt/hdt-cpp#5]
Hi,

after compiling `hdt-lib` compiling the tests (with `make tests`) resuls in the following compilation error.

``` bash
$ make tests
 [HDT] Compiling test tests/bit375.cpp
 [HDT] Compiling test tests/bitutiltest.cpp
 [HDT] Compiling test tests/cmp.cpp
tests/cmp.cpp: In member function ‘virtual unsigned char* MyIterator::next()’:
tests/cmp.cpp:33:65: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
   sprintf((char*)buffer, "AAA %015lld FINNN", (uint64_t) count++);
                                                                 ^
 [HDT] Compiling test tests/confm.cpp
/tmp/cc4opceY.o: In function `main':
confm.cpp:(.text.startup+0xc79): undefined reference to `hdt::LiteralDictionary::LiteralDictionary()'
confm.cpp:(.text.startup+0xc92): undefined reference to `hdt::LiteralDictionary::import(hdt::Dictionary*, hdt::ProgressListener*)'
confm.cpp:(.text.startup+0xd7b): undefined reference to `hdt::LiteralDictionary::save(std::ostream&, hdt::ControlInformation&, hdt::ProgressListener*)'
confm.cpp:(.text.startup+0xdf6): undefined reference to `hdt::LiteralDictionary::~LiteralDictionary()'
confm.cpp:(.text.startup+0xee1): undefined reference to `hdt::LiteralDictionary::~LiteralDictionary()'
collect2: error: ld returned 1 exit status
make: *** [tests/confm] Error 1
```

Cristian

**Comment by bendiken** [comment]
@CristianCantoro Could you re-try, please, with the current version of the library?

Also, in case the problem persists, we would need more information to reproduce it, as the project generally compiles fine on Ubuntu 14.04--it's what I compile on myself.

**Comment by RubenVerborgh** [comment]
Now also building tests on Travis: 554bf77bb8e916ddd6d5cc069a7c316cbc3c3a60, let's see how that goes: https://travis-ci.org/rdfhdt/hdt-cpp/builds/191244955. If it works, I think we can close this. (Travis is 12.04, but we test different gcc versions.)

**Comment by RubenVerborgh** [comment]
PS Even better would be actually executing the tests on Travis, but unsure whether they work.

**Comment by RubenVerborgh** [comment]
Tests compile on Travis.

**Comment by RubenVerborgh** [comment]
Now also running the tests: https://travis-ci.org/rdfhdt/hdt-cpp/builds/191248793

**Comment by RubenVerborgh** [comment]
Mmm, one of the tests runs indefinitely…

**Comment by RubenVerborgh** [comment]
Trying again with a subset of tests: https://travis-ci.org/rdfhdt/hdt-cpp/builds/191258192 (some tests seem to require input files)

**Comment by RubenVerborgh** [comment]
Almost there: https://travis-ci.org/rdfhdt/hdt-cpp/builds/191268520

**Comment by RubenVerborgh** [comment]
554bf77bb8e916ddd6d5cc069a7c316cbc3c3a60 has been merged to develop, so tests are compiled on Travis.

**Comment by mielvds** [comment]
Cool, thanks
