### ISSUE TITLE
Compile error: ‘serd_reader_read_source’ was not declared in this scope

### ISSUE THREAD

**Issue by jijino** [rdfhdt/hdt-cpp#110]
```
 [HDT] Compiling src/rdf/RDFParserSerd.cpp
src/rdf/RDFParserSerd.cpp: In member function ‘SerdSyntax hdt::RDFParserSerd::getParserType(hdt::RDFNotation)’:
src/rdf/RDFParserSerd.cpp:158:10: error: ‘SERD_NQUADS’ was not declared in this scope
   return SERD_NQUADS;
          ^
src/rdf/RDFParserSerd.cpp: In member function ‘virtual void hdt::RDFParserSerd::doParse(const char*, const char*, hdt::RDFNotation, bool, hdt::RDFCallback*)’:
src/rdf/RDFParserSerd.cpp:193:42: error: ‘serd_reader_read_source’ was not declared in this scope
    &libzSerdStream, input, SERD_PAGE_SIZE);
                                          ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unknown-warning-option" [enabled by default]
make[1]: *** [src/rdf/RDFParserSerd.o] Error 1
```

**Comment by sharpaper** [comment]
I also get this error when compiling branch `master`. I'm using Linux. Is there a minimum GCC requirement maybe?

**Comment by joernhees** [comment]
worked with gcc6 and serd 0.28.0 for me... wild guess: doesn't work with the apt serd version?

**Comment by sharpaper** [comment]
mmm yeah I have serd 0.26 (installed from the repositories)...

**Comment by joernhees** [comment]
maybe try:
```
wget https://github.com/drobilla/serd/archive/v0.28.0.tar.gz && tar -xvzf *.tar.gz && rm *.tar.gz && cd serd-* && ./waf configure && ./waf && sudo ./waf install
```

**Comment by sharpaper** [comment]
Thanks @joernhees. Upgrading libserd from v0.26 to v0.28 solved the issue for me, although I still see quite a lot of warnings. I think this issue can be closed after adding a "Dependencies" section in the README.

**Comment by LaurensRietveld** [comment]
Fixed by #120 and by documenting this version dep
